#!/bin/bash

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root" 
  exit 1
fi

source /etc/ec2-auto-shutdown/ec2-auto-shutdown-config
shutdown_after=`expr $shutdown_idle_minutes \* 60`
last_activity=`date +%s`
while true
do
  users_connected=$(netstat -tnpa | grep 'ESTABLISHED' | wc -l)

  if [ "$users_connected" -gt "0" ]; then
    last_activity=`date +%s`
  fi

  now=`date +%s`
  since_last_activity=`expr $now - $last_activity`
  if [ "$since_last_activity" -gt "$shutdown_after" ]; then
    shutdown now Shutdown initiated by ec2-auto-shutdown.
    sleep 60
  fi
  sleep 1
done
